JupiterOne/graph-azure

jest.config.js, package.json, src/azure/AzureClient.ts, src/azure/AzureClientError.ts, src/azure/graph/authenticate.ts, src/azure/graph/fetchOrganization.ts, src/index.ts, test/helpers/polly.ts, yarn.lock
The Azure graph client requires a global fetch function. cross-fetch was
introduced to satisfy this demand because it delegates to node-fetch. Once the
polyfill is in place, at the beginning of the program, there is no need for
direct references to the types.
=> Clarify polyfill

docs/jupiterone-io/graph-azure.md
This is required to allow reading member listings where the group contains an organization "Contact" type. I'd really like to have data returned from the test org that includes an org contact, but that requires a paid Office 365 account, to manage org data, as far as I can tell.
=> Add missing group member list reading perms

src/azure/resource-manager/BunyanLogPolicy.ts
We want to log header values so that we know which header we're sending
malformed, but we don't want to log header values that could be
sensitive. This is the first step towards reaching the first goal
without violating the second.
=> Log request header keys

src/converters/graph.test.ts, src/converters/graph.ts, src/synchronizers/synchronizeAccount.ts
User configuration error. We should still create the account entity and put it in the cache, but inform the user in the job log that it will be somewhat anemic.
=> Do not page when access to account org is denied

terraform/compute.tf, terraform/storage.tf, terraform/vars.tf
When not working on ingesting some resource or other, do not create them. The default is to create no expensive resources unless enabled.
=> Provide optional limits on Terraformed resources

CHANGELOG.md, package.json, src/synchronizers/syncronizeDatabaseResources.ts
This step does not complete in some large accounts. There are logs only up to about 6 minutes in, and then silence until minute 15 when the Lambda times out.
=> Add dbsync logging

CHANGELOG.md, src/steps/resource-manager/network/index.ts
Another duplicate relationship preventing a step from completing. This is a great feature of the SDK 😄 
```
Error: Duplicate _key detected (_key=/subscriptions/abc/resourceGroups/thegroup/providers/Microsoft.Network/loadBalancers/kubernetes|connects|/subscriptions/abc/resourceGroups/thegroup/providers/Microsoft.Compute/virtualMachineScaleSets/aks-agentpool-123-vmss/virtualMachines/0/networkInterfaces/aks-agentpool-123-vmss)
at DuplicateKeyTracker.registerKey (/opt/lifeomic/app/node_modules/@jupiterone/integration-sdk-runtime/dist/src/execution/jobState.js:11:19)
at /opt/lifeomic/app/node_modules/@jupiterone/integration-sdk-runtime/dist/src/execution/jobState.js:52:33
at Array.forEach (<anonymous>)
at Object.addRelationships (/opt/lifeomic/app/node_modules/@jupiterone/integration-sdk-runtim …
```
=> Fix duplicate load balancer -> nic relationships

CHANGELOG.md, src/steps/resource-manager/interservice/index.ts
@ndowmon here is an example of how it can be expensive to add tests for this change because I'd need to work through the details of getting multiple nics and/or multiple ip configurations on a single nic to prove this out. I think it will be worth having that eventually, but there are currently no tests at all for this particular step.
=> Avoid duplicate subnet -> vm relationships

CHANGELOG.md, docs/development.md, terraform/cosmosdb.tf, terraform/keyvault.tf, terraform/storage.tf, terraform/vars.tf
This PR enables developers to deploy `azurerm_storage_account`, `azurerm_cosmosdb_account`, and `azurerm_key_vault` resources with globally unique names. This enables multiple developers to deploy terraform at the same time with conflicting names.
=> Prefix globally unique tf resources with `developer_id`

test/integrationInstanceConfig.ts
Using environment variables in `/test/integrationInstanceConfig` causes polly to re-record certain API requests that contain configuration variables (such as `subscriptionId`). For now, hard-coding the `directoryId` and `subscriptionId` that are already in the polly recordings allows other developers to come in and pass tests locally.
A longer-term solution involves getting creative with polly matchers.
=> Hard-code test integration instance config

README.md, docs/development.md, package.json
Use `tfenv` deployment strategy as the only suggested deployment option. Usage: 
```sh
yarn tf init
yarn tf plan
yarn tf apply
yarn tf destroy
```
Remove references to using docker to deploy.
=> Add yarn tf command

docs/jupiterone.md, src/getStepStartStates.test.ts, src/getStepStartStates.ts, src/steps/resource-manager/authorization/__recordings__/active-directory-step-classic-administrators_3012456868/recording.har, src/steps/resource-manager/authorization/__recordings__/iterateClassicAdministrators_2362991753/recording.har, src/steps/resource-manager/authorization/client.test.ts, src/steps/resource-manager/authorization/client.ts, src/steps/resource-manager/authorization/constants.ts, src/steps/resource-manager/authorization/converters.test.ts, src/steps/resource-manager/authorization/converters.ts, src/steps/resource-manager/authorization/index.test.ts, src/steps/resource-manager/authorization/index.ts
From Microsoft ([reference](https://docs.microsoft.com/en-us/azure/role-based-access-control/classic-administrators)): 
> Microsoft recommends that you manage access to Azure resources using Azure role-based access control (Azure RBAC). However, if you are still using the classic deployment model, you'll need to use a classic subscription administrator role: Service Administrator and Co-Administrator.
This is useful to check who has classic administrator privileges or create rules to ensure there are no classic administrators.
I created a singleton `azure_classic_admin_group`, and relationships for `azure_classic_admin_group|HAS|<target_user>`. The relationships are mapped as opposed to direct, since the data returned from the `classicAdministrator` client has no user ID.
User:
```{ …
```
=> Add classic administrators

CHANGELOG.md
This screenshot shows v4.1.1. as the commit with hash `90668b4`. Matches the single commit of this PR.
=> typo & 4.1.1

CHANGELOG.md, src/steps/resource-manager/authorization/constants.ts, src/steps/resource-manager/authorization/converters.test.ts, src/steps/resource-manager/authorization/index.test.ts, src/steps/resource-manager/authorization/index.ts
Changes based on slack conversation: https://jptrone.slack.com/archives/C0174AZA75J/p1598375320074200
**Previously**
`azure_role_definition[AccessPolicy]--HAS-->azure_role_assignment[AccessRole]`
note: the direction was a typo/switched (was supposed to have been `<--HAS--`)
**Now**
`azure_role_definition[AccessRole]<--USES--azure_role_assignment[AccessPolicy]`
=> Update classes on role assignments & definitions

CHANGELOG.md, docs/jupiterone.md, src/steps/resource-manager/authorization/constants.ts, src/steps/resource-manager/authorization/index.test.ts, src/steps/resource-manager/authorization/index.ts, src/steps/resource-manager/compute/index.ts, src/steps/resource-manager/cosmosdb/index.ts, src/steps/resource-manager/databases/index.ts, src/steps/resource-manager/databases/mariadb/index.ts, src/steps/resource-manager/databases/mysql/index.ts, src/steps/resource-manager/databases/postgresql/index.ts, src/steps/resource-manager/databases/sql/index.ts, src/steps/resource-manager/key-vault/index.ts, src/steps/resource-manager/network/index.test.ts, src/steps/resource-manager/network/index.ts, src/steps/resource-manager/storage/index.ts, src/steps/resource-manager/utils/createResourceGroupResourceRelationship.test.ts, src/steps/resource-manager/utils/createResourceGroupResourceRelationship.ts, src/steps/resource-manager/utils/findOrBuildResourceEntityFromResourceId.test.ts, src/steps/resource-manager/utils/findOrBuildResourceEntityFromResourceId.ts, src/steps/resource-manager/utils/matchers.ts
The first couple commits are centralizing the `ROLE_ASSIGNMENT_SCOPE_TYPES_MAP` from the `authorization` steps into `RESOURCE_ID_TYPES_MAP`. That utility code can be used to identify any type and is super helpful in constructing direct relationships between resources.
The main change is in the final commit.
=> Add azure resource group to resource relationships

src/validateInvocation.test.ts, src/validateInvocation.ts
A little annoying issue - the reason we kept seeing `Provider authentication failed at undefined: undefined undefined` in the azure integration is we were re-throwing `IntegrationProviderAuthenticationError`s which are not idempotent. 
The constructor for `IntegrationProviderAuthenticationError` has the properties `cause`, `endpoint`, `status`, and `statusText`, but the class itself is a subclass of `IntegrationError` (which have the properties `message`, `code`, 'cause', and 'fatal').
It automatically generates an error message based on `Provider API failed at ${options.endpoint}: ${options.status} ${options.statusText}`. Since the Error itself has none of those properties, we (and the customer) is missing out on valuable error messages, and instead getting garbage.
=> Use IntegrationValidationError in validation check

CHANGELOG.md, docs/jupiterone.md, src/steps/resource-manager/storage/constants.ts, src/steps/resource-manager/storage/converters.test.ts, src/steps/resource-manager/storage/converters.ts, src/steps/resource-manager/storage/index.ts, src/steps/resource-manager/utils/findOrBuildResourceEntityFromResourceId.ts
Storage accounts have direct relationships to **Blobs**, **File Shares**, **Queues**, **Tables** and in some cases **Data Lakes** or other storage services. 
A storage account has a **Kind** property which can limit the types of storage services that can exist within a storage account,  including **Storage**, **BlobStorage,** **StorageV2**, and others. 
Previously, a storage account that had some **Blobs** and some **File Shares** would create two entities to represent the storage account. This PR creates a single `azure_storage_account` entity per storage account, and links the storage account to the `azure_resource_group` associated with the storage account.
Old graph:
New Graph:
=> Fix storage account relationships

CHANGELOG.md, docs/jupiterone.md, package.json, src/getStepStartStates.test.ts, src/getStepStartStates.ts, src/index.ts, src/steps/resource-manager/container-registry/__recordings__/iterateRegistries_3890134918/recording.har, src/steps/resource-manager/container-registry/__recordings__/iterateRegistryWebhooks_874434892/recording.har, src/steps/resource-manager/container-registry/__recordings__/resource-manager-step-container-registries_2250806650/recording.har, src/steps/resource-manager/container-registry/__recordings__/resource-manager-step-container-registry-webhooks_891010703/recording.har, src/steps/resource-manager/container-registry/__snapshots__/converters.test.ts.snap, src/steps/resource-manager/container-registry/client.test.ts, src/steps/resource-manager/container-registry/client.ts, src/steps/resource-manager/container-registry/constants.ts, src/steps/resource-manager/container-registry/converters.test.ts, src/steps/resource-manager/container-registry/converters.ts, src/steps/resource-manager/container-registry/index.test.ts, src/steps/resource-manager/container-registry/index.ts, src/steps/resource-manager/utils/findOrBuildResourceEntityFromResourceId.ts, terraform/container-registry.tf, yarn.lock
The Azure **Container Registry** service is equivalent to the Azure ECR service. 
The Container Registry client for Node.js does _not_ currently expose Repository.list or image/tag.list APIs, so I have ingested only `Registry` and `Webhook` entities (both of which are exposed in the SDK client _and_ as [terraform resources](https://www.terraform.io/docs/providers/azurerm/r/container_registry_webhook.html)).
=> Add container registry resources

CHANGELOG.md, package.json, src/getStepStartStates.test.ts, src/getStepStartStates.ts, src/index.ts, src/types.ts, src/validateInvocation.test.ts, src/validateInvocation.ts
Reverting the change from earlier. This change made previously-configured integrations stop ingesting resource manager resources. I feel that reverting this change is a smarter move than setting up a maintenance job to set `ingestResourceManager` to `true` on existing integrations.
=> Revert ingest resource manager flag

CHANGELOG.md, src/azure/resource-manager/client.ts, src/steps/resource-manager/api-management/client.ts, src/steps/resource-manager/batch/client.ts, src/steps/resource-manager/cdn/client.ts, src/steps/resource-manager/container-instance/client.ts, src/steps/resource-manager/container-registry/client.ts, src/steps/resource-manager/cosmosdb/client.ts, src/steps/resource-manager/databases/mariadb/client.ts, src/steps/resource-manager/databases/mysql/client.ts, src/steps/resource-manager/databases/postgresql/client.ts, src/steps/resource-manager/databases/sql/client.ts, src/steps/resource-manager/dns/client.ts, src/steps/resource-manager/event-grid/client.ts, src/steps/resource-manager/private-dns/client.ts, src/steps/resource-manager/redis-cache/client.ts, src/steps/resource-manager/service-bus/client.ts, src/steps/resource-manager/storage/client.ts
The typings on `ListResourcesEndpoint` and `ListAllResourcesEndpoint` have caused issues in the past when synthetic `resourceEndpoint` arguments are used in Azure service clients. Because of the imperfect typings, developers used a common pattern of type asserting on these endpoints. However, type asserting actually took away any real surety that proper types were used, and bugs such as creating a `linkNext` property where it should have been `listNext`.
Fixes #168
=> Stop casting ListResourcesEndpoint

CHANGELOG.md, package.json, src/index.ts, src/steps/active-directory/index.test.ts, src/steps/resource-manager/advisor/index.test.ts, src/steps/resource-manager/advisor/index.ts, src/steps/resource-manager/api-management/index.test.ts, src/steps/resource-manager/authorization/index.test.ts, src/steps/resource-manager/batch/index.test.ts, src/steps/resource-manager/cdn/index.test.ts, src/steps/resource-manager/container-instance/index.test.ts, src/steps/resource-manager/container-registry/index.test.ts, src/steps/resource-manager/dns/index.test.ts, src/steps/resource-manager/event-grid/index.test.ts, src/steps/resource-manager/network/index.test.ts, src/steps/resource-manager/private-dns/index.test.ts, src/steps/resource-manager/redis-cache/index.test.ts, src/steps/resource-manager/resources/index.test.ts, src/steps/resource-manager/security/index.test.ts, src/steps/resource-manager/service-bus/index.test.ts, src/steps/resource-manager/storage/index.test.ts, src/steps/resource-manager/subscriptions/index.test.ts, src/steps/resource-manager/utils/createResourceGroupResourceRelationship.test.ts, src/steps/resource-manager/utils/findOrBuildResourceEntityFromResourceId.test.ts, test/createMockAzureStepExecutionContext.ts, yarn.lock
Implement key normalization introduced in:  https://github.com/JupiterOne/sdk/pull/358
Azure IDs have inconsistent casing when returned from a variety of Azure APIs. Normalize Azure IDs to lowercase in order to ensure that the `DuplicateKeyTracker` and `jobState.findEntity()` functionality work properly for these `_key` values.
=> Add key lookup transformer

CHANGELOG.md, package.json, yarn.lock
This moves to the latest SDK to address a peer dependency warning in the deployment project, which had already moved to deploying this with SDK 5.0.0.
=> Release 5.8.1

CHANGELOG.md, src/steps/resource-manager/network/__recordings__/network-steps_2570137323/recording.har, src/steps/resource-manager/network/index.test.ts, src/steps/resource-manager/network/index.ts, terraform/compute.tf
- 6.4 Ensure that Network Security Group Flow Log retention period is 'greater than 90 days' (Automated)
- This benchmark aims to ensure that Network Security …
=> Collecting Diagnostic Settings Entities and Relationships for Network Security Groups

CHANGELOG.md, src/azure/resource-manager/client.test.ts, src/azure/resource-manager/client.ts
The RM client was not properly handling system / `node-fetch` errors, which caused errors to be exposed like:
```
Error: Provider API failed at storage.tables: undefined undefined
```
The proper error message should have been something like 
```
Error: Provider API failed at storage.tables: ECONNRESET Connection reset by server
```
or something similar.
More PRs to come, including retries and re-using this logic in Azure AD (Graph) APIs.
=> Fix how RM exposes ECONNRESET and node-fetch errors

CHANGELOG.md, src/azure/resource-manager/client.test.ts, src/azure/resource-manager/client.ts
Add mechanism to Azure Resource Manager client to retry non-Azure `RestError` errors, including `RestError`.
=> Retry non-Azure RM API errors

CHANGELOG.md, src/azure/graph/client.test.ts, src/azure/graph/client.ts, src/azure/resource-manager/client.test.ts, src/steps/active-directory/client.ts
Add a `request` function to the Azure Graph API, which centralizes requests and error handling for `GraphRequest.get()` requests, used to fetch Azure Active Directory resources.
Also add a `retryRequest` function to retry requests for Azure Graph API.
=> Retry azure graph API calls

CHANGELOG.md, src/steps/resource-manager/container-registry/__recordings__/resource-manager-step-container-registries_2250806650/recording.har, src/steps/resource-manager/container-registry/index.test.ts, src/steps/resource-manager/container-registry/index.ts, terraform/container-registry.tf
-  5.3 Ensure that Diagnostic Logs are enabled for all services which support it. (Automated)
- Unlike diagnostic logs that capture activity for the …
=> Diagnostic Settings for Azure Container Registry

CHANGELOG.md, cli/commands/documentDiagnosticSettings.ts, docs/jupiterone.md, src/steps/resource-manager/api-management/index.ts, src/steps/resource-manager/batch/index.ts, src/steps/resource-manager/cdn/index.ts, src/steps/resource-manager/container-registry/index.ts, src/steps/resource-manager/databases/index.ts, src/steps/resource-manager/databases/postgresql/index.ts, src/steps/resource-manager/databases/sql/index.ts, src/steps/resource-manager/event-grid/index.ts, src/steps/resource-manager/key-vault/constants.ts, src/steps/resource-manager/key-vault/index.ts, src/steps/resource-manager/monitor/converters.ts, src/steps/resource-manager/network/index.ts, src/steps/resource-manager/subscriptions/constants.ts, src/steps/resource-manager/subscriptions/index.ts, src/steps/resource-manager/utils/createDiagnosticSettingsEntitiesAndRelationshipsForResource.ts
This does a better job of scoping the diagnostic settings log categories, which are different for each resource.
=> Add log category documentation to diagnostic settings

CHANGELOG.md, src/steps/resource-manager/compute/index.test.ts, src/steps/resource-manager/compute/index.ts
```
- Changed `_key` property on `azure_vm_uses_storage_account` to fix
`DuplicateKeyError`s when multiple data disks point to the same storage
account.
```
=> Fix DuplicateKeyError for azure_vm_uses_storage_account

CHANGELOG.md, src/steps/resource-manager/storage/client.ts, src/steps/resource-manager/storage/converters.ts
```
- Handle errors thrown from `getBlobServiceProperties()` instead of allowing
storage account step to fail.
```
=> Handle errors thrown from getBlobServiceProperties()

CHANGELOG.md, src/steps/resource-manager/policy/findOrCreatePolicyDefinitionEntityFromAssignment.ts
- Changed `_key` property for
`azure_policy_set_definition|contains|azure_policy_definition` relationship to
use `policyDefinitionReference.policyDefinitionReferenceId` instead of
`policyDefinitionReference.policyDefinitionId`. The same
`azure_policy_definition` can be referenced more than once in an
`azure_policy_set_definition` using different `parameter` properties.
Previously, the relationship `_key` used the `policyDefinitionId`, which threw
`DuplicateKeyError`s Example:
```json
{
"policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/b954148f-4c11-4c38-8221-be76711e194a",
"parameters": {
"operationName": {
"value": "Microsoft.Network/networkSecurityGroups/delete"
}
},
"policyDefinitionReferenceId": "CISv110x5x2x3",
"groupNames": [
"CIS_Azure_1.1.0_5.2.3"
]
},
{ …
```
=> Fix policy_set_definition|CONTAINS|policy_definition duplicate key errors

CHANGELOG.md, package.json
```
- Changed logic for fetching tables/queues/fileShares of `Premium` tier
storageV1/storageV2 `azure_storage_account`s, because only `Standard` tier
storage accounts support tables/queues/fileShares.
```
=> Release 5.23.3

CHANGELOG.md, src/steps/resource-manager/policy/client.ts, src/steps/resource-manager/policy/findOrCreatePolicyDefinitionEntityFromAssignment.ts, src/steps/resource-manager/storage/client.ts
```
- Added try/catch logic to `AzurePolicyClient` methods for policy definitions &
policy set definitions so step does not fail from 404s.
```
=> Add try/catch logic to AzurePolicyClient methods for policy definitions

src/steps/resource-manager/policy/findOrCreatePolicyDefinitionEntityFromAssignment.ts
When the policy definition is not found because of 404s, it's unclear why. I am wondering whether, for example, we are getting policy definitions with ID like `/SUBSCRIPTIONS/${s-id}/providers/Microsoft.Authorization/policyDefinitions/${pd-id}`.
=> Add logger.warn to expose policyDefinitionId

CHANGELOG.md, src/steps/resource-manager/policy/client.ts, src/steps/resource-manager/policy/findOrCreatePolicyDefinitionEntityFromAssignment.ts
```
- Added logic to handle `policyDefinition` IDs that are sourced from management
groups.
```
During the original implementation, it wasn't clear that there were management group-based policy definitions, and these were mishandled causing some integrations to fail. Now that these are properly handled, I tore out a good amount of the safety netting and `logger.warn` statements so that this step _does_ fail when the API returns 4xx/5xx responses. See @austinkelleher 's comments in a previous PR https://github.com/JupiterOne/graph-azure/pull/301#pullrequestreview-641402702
=> Handle policyDefinitionId sourced from management groups

CHANGELOG.md, package.json
```
- Added logic to handle `policyDefinition` IDs that are sourced from management
groups.
=> Release 5.23.6

CHANGELOG.md, docs/jupiterone.md, package.json, src/getStepStartStates.test.ts, src/getStepStartStates.ts, src/index.ts, src/steps/resource-manager/appservice/__recordings__/iterateAppServicePlans_4213262849/recording.har, src/steps/resource-manager/appservice/__recordings__/iterateApps_207803837/recording.har, src/steps/resource-manager/appservice/__recordings__/rm-appservice-app-plan-relationships_169005199/recording.har, src/steps/resource-manager/appservice/__recordings__/rm-appservice-app-service-plans_1428281048/recording.har, src/steps/resource-manager/appservice/__recordings__/rm-appservice-apps_1396228188/recording.har, src/steps/resource-manager/appservice/client.test.ts, src/steps/resource-manager/appservice/client.ts, src/steps/resource-manager/appservice/constants.ts, src/steps/resource-manager/appservice/converters.ts, src/steps/resource-manager/appservice/index.test.ts, src/steps/resource-manager/appservice/index.ts, terraform/appservice.tf, yarn.lock
The Azure endpoint for `Function App` resources (`providers/Microsoft.Web/sites`) is generic, and returns both function apps (`azure_function_app`) and web apps (`azure_web_app`). I chose to create these as two different `_type`s, because they're well segmented in the azure console, so normalizing on a single `_type` (like `azure_app`) seems super confusing.
That said, the best differentiator from the API response is the `type` property, which is just a comma-separated list that may include `functionapp` or `app`. Don't completely love that as a differentiator, so let me know if you think this should have been done differently.
=> Ingest app service apps

CHANGELOG.md, src/steps/resource-manager/storage/converters.ts
Fixes #335 
Note that although the property `networkRuleSet.ipRules` is an array that has both an `action` property (e.g. `"allow"`) and an `iPAddressOrRange` property, investigation in the UI shows that rules can only be defined when **All networks** is selected in the **Allow access from** field, not the **Selected networks** property.
Allow access from **All networks** (no option to provide IP address / range)
Allow access from **Selected networks** (option to provide IP address / range. Defaults to **Allow**)
Hence, it's safe to assume that when `ipRules` is populated, the rules are of type `allow`, and the property `azure_storage_account.networkRuleSet.allowedIpAddresses` is appropriate.
```
- Added the following property to `azure_storage_account`:
- …
```
=> Add azure_storage_account.networkRuleSet.allowedIpAddresses

CHANGELOG.md, src/steps/resource-manager/compute/converters.test.ts, src/steps/resource-manager/compute/converters.ts
Partially solves #341 by allowing j1ql queries on extension settings where the continuous delivery information resides.
=> Add new vm extension properties to get things like CD settings

CHANGELOG.md, docs/jupiterone.md, package.json, src/getStepStartStates.test.ts, src/getStepStartStates.ts, src/index.ts, src/steps/resource-manager/management-groups/__recordings__/getManagementGroup_2914528671/recording.har, src/steps/resource-manager/management-groups/__recordings__/rm-management-groups_1477189011/recording.har, src/steps/resource-manager/management-groups/__recordings__/validateManagementGroupStepInvocation-badCredentials_2778872183/recording.har, src/steps/resource-manager/management-groups/__recordings__/validateManagementGroupStepInvocation-success_1089248527/recording.har, src/steps/resource-manager/management-groups/client.test.ts, src/steps/resource-manager/management-groups/client.ts, src/steps/resource-manager/management-groups/constants.ts, src/steps/resource-manager/management-groups/converters.ts, src/steps/resource-manager/management-groups/index.test.ts, src/steps/resource-manager/management-groups/index.ts, src/steps/resource-manager/policy-insights/index.test.ts, src/steps/resource-manager/policy/index.test.ts, src/types.ts, yarn.lock
This introduces a new config field `ingestManagementGroups` that should be used like the `ingestActiveDirectory` config field. However, it may be best to remove `intestManagementGroups` and just ingest them when `ingestActiveDirectory` is set to `true`.
Here's a look at the management group structure in Azure:
=> 339 management groups

CHANGELOG.md, src/steps/resource-manager/authorization/index.ts
```
- Fixed a bug introduced in `5.25.1` where the
`rm-authorization-classic-administrators` step no longer had a dependency on
the `ad-account` step, causing `ACCOUNT_ENTITY_NOT_FOUND` errors.
```
=> Add ad-account step dep to classic admins step

CHANGELOG.md, package.json
```
- Fixed a bug introduced in `5.25.1` where the
`rm-authorization-classic-administrators` step no longer had a dependency on
the `ad-account` step, causing `ACCOUNT_ENTITY_NOT_FOUND` errors.
```
=> Changelog for 5.26.1

CHANGELOG.md, src/steps/resource-manager/policy/converters.ts
Fixes #375 
```
- New properties added to resources:
| Entity                    | Properties                                  |
| ------------------------- | ------------------------------------------- |
| `azure_policy_definition` | Automatically convert `metadata` to J1 tags |
```
=> Add metadata tags to azure_policy_definition

CHANGELOG.md, src/steps/resource-manager/compute/index.ts
Fixes #374 
```
- Fixed a bug where the compute galleries execution handler was not invoked, and
instead the VM images execution handler was invoked twice. This caused
DuplicateKeyErrors in either the compute galleries step or the VM images step.
```
=> Fix compute galleries step

CHANGELOG.md, docs/jupiterone.md, src/steps/resource-manager/compute/__recordings__/rm-compute-virtual-machine-image-relationships_3626092588/recording.har, src/steps/resource-manager/compute/constants.ts, src/steps/resource-manager/compute/index.test.ts, src/steps/resource-manager/compute/index.ts
Fixes #387 
```
| Source               | \_class | Target                       |
| -------------------- | ------- | ---------------------------- |
| `azure_vm`           | `USES`  | `azure_shared_image_version` |
```
=> 387 vm shared image version relationships

CHANGELOG.md, package.json
```
- Moved `@microsoft/microsft-graph-types` from dev to direct dependency, which
was previously causing types to fail on dependent projects after exporting
`clients.GraphClient` in `v5.27.1`.
```
=> Add @microsoft/microsoft-graph-types to direct dep

CHANGELOG.md, docs/jupiterone.md, src/getStepStartStates.test.ts, src/getStepStartStates.ts, src/steps/resource-manager/compute/__recordings__/rm-compute-shared-image-version-source-relationships_3822310037/recording.har, src/steps/resource-manager/compute/constants.ts, src/steps/resource-manager/compute/converters.test.ts, src/steps/resource-manager/compute/converters.ts, src/steps/resource-manager/compute/index.test.ts, src/steps/resource-manager/compute/index.ts
Fixes #389
```
| Source     | \_class     | Target                       |
| ---------- | ----------- | ---------------------------- |
| `azure_vm` | `GENERATED` | `azure_shared_image_version` |
- Lowercase the `azure_vm._key` property to allow for mapped relationships
across different J1 subscriptions.
```
=> 389 image version source

CHANGELOG.md
```
| Source                   | \_class     | Target                       |
| ------------------------ | ----------- | ---------------------------- |
| `azure_vm`               | `GENERATED` | `azure_shared_image_version` |
| `azure_keyvault_service` | `ALLOWS`    | `ANY_PRINCIPAL`              |
- Lowercase the `azure_vm._key` property to allow for mapped relationships
across different J1 subscriptions.
```
=> Changelog for 5.30.0

CHANGELOG.md, src/steps/active-directory/__recordings__/ad-group-members_1372959748/recording.har, src/steps/active-directory/converters.test.ts, src/steps/active-directory/converters.ts, src/steps/active-directory/index.test.ts, src/steps/active-directory/index.ts
I noticed when working on a blog post that the mapped relationships we're creating here are unnecessary and not as reliable as direct relationships.
```
- Changed `azure_group_has_member` relationships from mapped to direct, because
group members always exist in the same directory as the group.
```
=> Change azure_group_has_member relationships from mapped to direct

CHANGELOG.md, src/azure/graph/client.ts, src/steps/active-directory/__recordings__/ad-user-registration-details-403_2267542617/recording.har, src/steps/active-directory/index.test.ts
We are seeing the following errors from the `ad-user-registration-details` step, which should be reported directly to the user but _not_ to operators.
> `Provider API failed at https://graph.microsoft.com/beta/reports/credentialUserRegistrationDetails: 403 Calling principal does not have required MSGraph permissions Reports.Read.All`
```
- Throw `IntegrationProviderAuthorizationError` on 403 response in `GraphClient`
```
=> Throw authorization error on 403 in GraphClient

CHANGELOG.md, src/steps/resource-manager/policy/findOrCreatePolicyDefinitionEntityFromAssignment.ts
We are seeing instances in production where the policy definition actually starts with `/providers/Microsoft.Management/managementgroups/`, which is causing us to throw the error `The policy definition  <<POLICY_DEFINITION_ID>> does not match any known sources`
```
- Identify policy definition source (subscription, management group, or
built-in) using a case-insensitive switch statement, since Azure resource IDs
do not use consistent casing.
```
=> Use case-insensitive switch statement for policy definition source

docs/jupiterone.md
We get enough requests from these integration configs that I think it's about time we start to standardize and publish troubleshooting tips.
Would love to hear feedback from CS / Solutions about where to put these troubleshooting tips. Are these appropriate in the graph projects themselves? If so, do they belong in `/docs/jupiterone.md`? If so, is this the right place? (After both the **In Azure** section and the **In JupiterOne** section)?
=> Add *Troubleshooting Auth Issues* section to docs

CHANGELOG.md, src/steps/resource-manager/authorization/index.test.ts, src/steps/resource-manager/compute/index.test.ts, src/steps/resource-manager/key-vault/index.test.ts
```
- Used `expect().toTargetEntities()` matcher from SDK, and removed local
implementations of `.toTargetEntities()` and
`.toCreateValidRelationshipsToEntities()`
```
=> Use toTargetEntities matcher from SDK

CHANGELOG.md, package.json, src/azure/resource-manager/client.ts
```
- Stop throwing
`Provider API failed at storage.*: AccountIsDisabled The specified account is disabled.`
on storage blob/queue/table/file steps
- Stop throwing
`Provider API failed at *.*: DisallowedOperation The current subscription type is not permitted to perform operations on any provider namespace. Please use a different subscription.`
on steps
=> Silence additional sentry issues

CHANGELOG.md, docs/jupiterone.md, package.json, yarn.lock
```
- Bumped `@jupiterone/integration-sdk-*@6.22.1`. This included new functionality
to the `IntegrationError` classes that better segregates errors coming from
different steps
```
=> Bump @jupiterone/integration-sdk-*@6.22.1

docs/jupiterone.md, jupiterone/questions/questions.yaml, src/steps/resource-manager/appservice/__recordings__/rm-appservice-app-plan-relationships_169005199/recording.har, src/steps/resource-manager/appservice/__recordings__/rm-appservice-apps_1396228188/recording.har, src/steps/resource-manager/appservice/client.ts, src/steps/resource-manager/appservice/converters.ts, src/steps/resource-manager/appservice/index.ts, src/validateInvocation.test.ts
This PR adds the following (new) benchmarks:
- 9.1 Ensure App Service Authentication is set on Azure App Service (Automated)
- 9.2 Ensure web app redirects all HTTP traffic to HTTPS in Azure App Service (Automated)
- 9.3 Ensure web app is using the latest version of TLS encryption (Automated)
- 9.4 Ensure the web app has 'Client Certificates (Incoming client certificates)' set to 'On' (Automated)
- 9.5 Ensure that Register with Azure Active Directory is enabled on App Service (Automated)
- 9.6 Ensure that 'PHP version' is the latest, if used to run the web app (Manual)
- 9.7 Ensure that 'Python version' is the latest, if used to run the web app (Manual)
- 9.8 Ensure that 'Java version' is the latest, if used to run the web app (Manual)
- 9.9 Ensure that 'HTTP Version' is the latest, if …
=> INT-1782 - Add AppServices (Section 9) CIS benchmarks

CHANGELOG.md, package.json, src/steps/resource-manager/container-services/converters.ts, src/steps/resource-manager/container-services/index.ts
Introduced with the recent `azure_kubernetes_cluster` entities.
```
- Stopped creating `azure_kubernetes_cluster` entities that have no `id`
property
```
=> Stop creating azure_kubernetes_cluster entities with no id property

CHANGELOG.md, package.json, src/steps/resource-manager/container-services/client.ts, src/steps/resource-manager/container-services/index.ts
```
- Stopped using the `callback` version of the
`ContainerServiceClient.managedClusters.list(callback)` API
=> Stop using the ContainerServiceClient.managedClusters.list(callback) interface

src/steps/resource-manager/cosmosdb/converters.test.ts, src/steps/resource-manager/cosmosdb/converters.ts, src/steps/resource-manager/utils/createResourceGroupResourceRelationship.test.ts
added a 'function' property to the cosmosdb step to conform with the 'Service' class
example error:
```
(stepId=rm-cosmosdb-sql-databases, errorId=01aa7a34-9efb-41d5-81ea-6d72377fa61e)
Error: Entity fails to validate as class 'Service':
[
{
"instancePath": "",
"schemaPath": "#/allOf/1/required",
"keyword": "required",
"params": {
"missingProperty": "function"
},
"message": "must have required property 'function'"
}
]
at Object.validateEntityWithSchema (/Users/jfisher/Tools/graph-azure/node_modules/@jupiterone/data-model/src/validateEntityWithSchema.ts:15:13)
at Object.createIntegrationEntity (/Users/jfisher/Tools/graph-azure/node_modules/@jupiterone/integration-sdk-core/src/data/createIntegrationEntity.ts:103:5)
at Object.createAccountEntity …
```
=> Fixing Cosmosdb account bug

CHANGELOG.md, src/steps/resource-manager/interservice/index.ts
The finding/reasoning is described in-depth in the associated [Jira ticket](https://jupiterone.atlassian.net/browse/INT-2777).
This PR prevents multiple use of the same subnet thus not letting the duplicate key error occur.
=> INT-2777 - Fix for subnet has vm duplicate key in relationships

src/steps/active-directory/client.ts, src/steps/active-directory/index.test.ts
The /reports/credentialUserRegistrationDetails endpoint is only available to
premium azure instances. If the instance is not premium, users should not
see the error in their job logs. They currently are because we were not
awaiting the response from the endpoint.
=> INT-3890 Do not log reports errors to users

docs/jupiterone.md
1. Recommend "Configure Subscription Instances"
2. (bonus) Number the "In JupiterOne" configuration settings to more easily follow/reference steps
3. (bonus) note that `azure_user`, `azure_user_group`, and `azure_service_principal` entities are ingested when "Ingest Active Directory" is checked, and that `azure_management_group` entities are ingested when "Configure Subscription Instances" is checked
Old docs: https://github.com/JupiterOne/main/docs/jupiterone.md
New docs: https://github.com/JupiterOne/graph-azure/blob/int-4029-update-docs-to-explain-subscription-id/docs/jupiterone.md
=> Update docs to recommend 'Configure Subscription Instances'

docs/jupiterone.md, jupiterone/questions/questions.yaml, src/steps/resource-manager/management-groups/constants.ts, src/steps/resource-manager/management-groups/index.ts
Although we have long been creating relationships between `azure_management_group` and `azure_subscription`, the SDK recently added support for documenting mapped relationships produced by integration steps. 
---
The following mapped relationships are created:
| Source Entity `_type`    | Relationship `_class` | Target Entity `_type`  | Direction |
| ------------------------ | --------------------- | ---------------------- | --------- |
| `azure_management_group` | **HAS**               | `*azure_subscription*` | FORWARD   |
=> Add mgmt group -> subscription mapped relationship metadata

CHANGELOG.md, src/steps/resource-manager/dns/index.test.ts, src/steps/resource-manager/dns/index.ts, src/steps/resource-manager/private-dns/index.test.ts, src/steps/resource-manager/private-dns/index.ts
Looks like it’s not possible to have DNS zones if the subscription has not registered the Microsoft.Network resource provider. I confirmed this by doing the following:
1. Unregister the Microsoft.Network provider from an active Azure subscription
2. Add a DNS Zone resource to the Azure subscription
a. I noticed that the Microsoft.Network provider was automatically switched from status Unregistered → Registered
3. Tried again to switch the Microsoft.Network provider status from Registered → Unregistered. It would not allow me to unregister while there were existing resources for the provider. (**`Error unregistering resource provider`**`The subscription cannot be unregistered from resource namespace 'microsoft.network'. Please delete existing resources for the provider.`)
Since that’s …
=> Stop printing 'UNREGISTERED_PROVIDER' messages in DNS Zone steps

.github/workflows/build.yml
We used to only fetch the latest 2 commits for versioning since HEAD-1 was the tagged commit. This leads to Auto not having visibility on all commits. We now fetch the entire commit history to allow Auto to properly create the changelog.
=> Update fetch-depth for Auto

docs/jupiterone.md, src/steps/resource-manager/frontdoor/constants.ts
This PR fixes a bug with the `azure_frontdoor_routing_rule`. This entity was previously using the `Route` class which is not in the data-model.
This causes an error to be thrown and the step to fail. The entity has been updated to use the `Rule` class. This isn't a breaking change since previously this entity would have never been able to be created.
=> fix(int-6429): update routing rule to rule class

src/steps/resource-manager/subscriptions/client.ts
Added support for pagination of the API that fetches all subscriptions from a specific Active Directory.
This allows to fetch more than just a single page of subscriptions (1000 subscriptions).
It is used by the instances that have Configure Subscription instances set on instance setup.
=> Azure FetchSubscriptions Pagination

src/azure/resource-manager/client.test.ts, src/azure/resource-manager/client.ts
When an API error ocurred related to an AzureRestError, it was displayed as:
`Provider API failed at policyInsights.policyStates: undefined undefined`
Now we get:
`Provider API failed at policyInsights.policyStates: AuthorizationFailed The client '[...]' with object id '[...]' does not have authorization to perform action 'Microsoft.PolicyInsights/policyStates/queryResults/read' over scope '/subscriptions/[...]' or the scope is invalid. If access was recently granted, please refresh your credentials.`
=> Fix(INT-6993): Some provider API Errors where being displayed incorrectly

src/__recordings__/getStepStartStates_2244155193/recording.har, src/getStepStartStates.test.ts, src/getStepStartStates.ts
Disabled all the steps for subscriptions named 'Access to Azure Active Directory'
These subscriptions do NOT host Azure AD. These are legacy subscriptions that can no longer be managed by customer portal. We decided not to execute any step, just show an event.
If (almost) any step executes we get:
` The current subscription type is not permitted to perform operations on any provider namespace. Please use a different subscription.`
More info: [legacy subscriptions](https://www.jasonfritts.me/2020/04/07/what-is-the-access-to-azure-active-directory-subscription-for/#:%7E:text=The%20%E2%80%9CAccess%20to%20Azure%20Active%20Directory%E2%80%9D%20subscriptions%20are%20a%20legacy,portal.azure.com)
=> Int 7422 disable steps legacy subscriptions

src/steps/resource-manager/management-groups/index.ts
Jira issue - https://jupiterone.atlassian.net/browse/INT-8687
TLDR, The azure integration is creating an entity from a relationship but the way its being created it is setting a _key that is different from the actual entity so the mapper can not adopt the initial entity.
Note that id and key are the same value on Klarna
=> Change target filter key to id

src/steps/active-directory/client.ts
All integrations with more that 185k users would fail because this. 
More info on paging: https://learn.microsoft.com/en-us/graph/paging
We were querying 
`ttps://graph.microsoft.com/v1.0/users?$select=businessPhones%2cdisplayName%2cgivenName%2cjobTitle%2cmail%2cmobilePhone%2cofficeLocation%2cpreferredLanguage%2csurname%2cuserPrincipalName%2cid%2cuserType%2caccountEnabled%2cbusinessPhones%2cdisplayName%2cgivenName%2cjobTitle%2cmail%2cmobilePhone%2cofficeLocation%2cpreferredLanguage%2csurname%2cuserPrincipalName%2cid%2cuserType%2caccountEnabled%2cbusinessPhones%2cdisplayName%2cgivenName%2cjobTitle%2cmail%2cmobilePhone%2cofficeLocation%2cpreferredLanguage%2csurname%2cuserPrincipalName%2cid%2cuserType%2caccountEnabled%2cbusinessPhones%2cdisplayName%2cgivenName%2cjobTitle%2cmail%2cmobilePhone% …
=> Corrected pagination of ad-users

src/steps/resource-manager/key-vault/client.ts
"RestError: AKV10032: Invalid issuer. Expected one of https://sts.windows.net/5ae1af62-9505-4097-a69a-c1553ef7840e/, https://sts.windows.net/f8cdef31-a31e-4b4a-93e4-5f571e91255a/, https://sts.windows.net/e2d54eb5-3869-4f70-8578-dee5fc7331f4/, found https://sts.windows.net/e5385570-36f1-4d50-aaf8-db2f87aa884a/. \n[...]"
We are requesting the keys with the wrong tenant/application. All of our integrations are single tenant based, so it would be impossible to ingest!
=> Handle key and secret permissions errors

src/steps/resource-manager/api-management/index.test.ts, src/steps/resource-manager/api-management/index.ts, src/steps/resource-manager/batch/index.test.ts, src/steps/resource-manager/batch/index.ts, src/steps/resource-manager/cdn/index.test.ts, src/steps/resource-manager/cdn/index.ts, src/steps/resource-manager/container-registry/index.test.ts, src/steps/resource-manager/container-registry/index.ts, src/steps/resource-manager/databases/index.ts, src/steps/resource-manager/databases/mariadb/index.test.ts, src/steps/resource-manager/databases/mysql/index.test.ts, src/steps/resource-manager/databases/postgresql/index.test.ts, src/steps/resource-manager/databases/postgresql/index.ts, src/steps/resource-manager/databases/sql/index.test.ts, src/steps/resource-manager/databases/sql/index.ts, src/steps/resource-manager/event-grid/index.test.ts, src/steps/resource-manager/event-grid/index.ts
Removed previously added dependsOn storageSteps.STORAGE_ACCOUNTS. While the steps do require the storageAccounts to be ingested in order to create the relationship between a diagnosticSetting and its storage account, it doesn't make sense for the step to be disabled if storage account is.
Therefore, for now, I'm removing the dependsOn I added, and enabling the dependencyGraphId: 'last' so that we can control on the tests that if the storageAccount exists, the relationship gets created, and to improve the chances we create the relationship on an actual run.
Further work might be needed to split the diagnosticsettings logic for all steps.
=> Remove previously added depends on
