package.json
src/converters/resources.test.ts
src/converters/resources.ts
src/converters/utils.test.ts
src/converters/utils.ts
src/jupiterone/entities.ts
yarn.lock

This is waiting on a release of the integration SDK.

Add some compute resource details

---

src/azure/fetchBatchOfGroupMembers.ts

I'd like to think through this more (handling 403 responses and how to report them back to users, other intermittent errors that should certainly not lead to the deletion of data), but this should break the infinite loop.

Handle failed request in fetch groups

---

.travis.yml
docs/development.md
docs/tagging.md
package.json
src/azure/createAzureWebLinker.test.ts
src/azure/createAzureWebLinker.ts
src/azure/resource-manager/ResourceManagerClient.test.ts
src/azure/resource-manager/ResourceManagerClient.ts
src/azure/resource-manager/__recordings__/iterateStorageAccounts_3417106798/recording.har
src/azure/resource-manager/__recordings__/iterateStorageBlobContainers_1342981129/recording.har
src/converters/relationships.ts
src/converters/resources/storage.test.ts
src/converters/resources/storage.ts
src/index.test.ts
src/index.ts
src/jupiterone/entities.ts
src/synchronizers/synchronizeStorageAccounts.ts
terraform/main.tf
yarn.lock

Ingests Blob containers. Depends on a release of the integration SDK. Still need to handle File, Queue, and Table storage services, though that should be getting easier to do with these changes setting up for it. Also need to get more details about the Blob service containers (like S3 buckets), such as policies etc.

Ingest storage accounts

---

src/synchronizers/synchronizeStorageAccounts.ts

This adds logging to help investigate why the blob service does not appear to be processed for a customer.

Add logging

---

jest.config.js
src/azure/resource-manager/BunyanLogPolicy.ts
src/azure/resource-manager/ResourceManagerClient.test.ts
src/azure/resource-manager/ResourceManagerClient.ts
src/initializeContext.ts

Log all request and throttling responses.

Add BunyanLogPolicy to ResourceManagerClient

---

src/azure/resource-manager/BunyanLogPolicy.ts
src/azure/resource-manager/ResourceManagerClient.ts
src/synchronizers/synchronizeStorageAccounts.ts

This should address all of the logs I said I would add in the related Jira ticket.

Additional Logs

---

src/azure/AzureClient.test.ts
src/azure/AzureClient.ts
src/azure/fetchBatchOfGroupMembers.ts
src/azure/fetchBatchOfResources.ts
src/converters/graph.test.ts
src/synchronizers/synchronizeGroupMembers.ts
src/types.ts

User configuration error, should be reported in the job log but not page.

Do not page when access to group members is denied

---

package.json
src/synchronizers/synchronizeStorageAccounts/oldData.ts
src/synchronizers/syncronizeComputeResources.ts
src/synchronizers/syncronizeDatabaseResources.ts
yarn.lock

Pulling in latest TypeScript and working around problems it still has inferring types 😢

Update to latest TypeScript

---

docs/jupiterone-io/graph-azure.md
jest.config.js
package.json
src/azure/resource-manager/ResourceManagerClient.ts
src/converters/relationships.ts
src/converters/resources/network.ts
src/jupiterone/entities.ts
src/jupiterone/relationships.ts
src/synchronizers/syncronizeComputeResources.ts
yarn.lock

Add support for LB entities and relationships

---

package.json
src/azure/resource-manager/BunyanLogPolicy.ts
src/azure/resource-manager/ResourceManagerClient.test.ts
src/azure/resource-manager/ResourceManagerClient.ts
src/azure/resource-manager/__recordings__/iterateStorageBlobContainersRetry_3932758613/recording.har
yarn.lock

Please consider the approach documented in the code. I was able to run the new test to work all this out, but I could not keep it enabled because replaying would take over 5 minutes.

Handle 429 failure

---

docs/jupiterone-io/graph-azure.md
package.json
src/azure/resource-manager/ResourceManagerClient.ts
src/azure/resource-manager/client.ts
src/converters/resources/storage.ts
src/index.test.ts
src/index.ts
src/synchronizers/synchronizeCosmosDBAccounts/__recordings__/iterateAccounts_2980472493/recording.har
src/synchronizers/synchronizeCosmosDBAccounts/__recordings__/iterateSQLDatabases_4172854763/recording.har
src/synchronizers/synchronizeCosmosDBAccounts/client.test.ts
src/synchronizers/synchronizeCosmosDBAccounts/client.ts
src/synchronizers/synchronizeCosmosDBAccounts/converters.test.ts
src/synchronizers/synchronizeCosmosDBAccounts/converters.ts
src/synchronizers/synchronizeCosmosDBAccounts/index.ts
terraform/compute.tf
terraform/cosmosdb.tf
terraform/storage.tf
terraform/vars.tf
yarn.lock

Lots of refactoring, working toward clearer code.

Ingest Cosmos DB SQL databases

---

src/synchronizers/syncronizeComputeResources.ts

We need to break up the processing as we go along so that unrelated resources are not in the same synchronization step. This gets there some of the way for compute resources by grouping things a bit, and only processing virtual networks when we get them.

Ignore virtual networks on 502

---

src/azure/resource-manager/ResourceManagerClient.test.ts
src/azure/resource-manager/ResourceManagerClient.ts
src/azure/resource-manager/__recordings__/iterateVirtualMachineDisks_438678801/recording.har
src/converters/resources/compute.test.ts
src/converters/resources/compute.ts

Updated to include a recording of the response for a disk that includes the `encryption` information. This leverages the disk created for the VM in the Terraform.

Ingest disk encrypted status

---

CHANGELOG.md
package.json

The move to GitHub actions required one more change.

Fix package deployment

---

docs/development.md

Based on working to get @ndowmon going on development.

Update docs for new developers

---

CHANGELOG.md
docs/jupiterone.md
package.json
src/getStepStartStates.test.ts
src/getStepStartStates.ts
src/index.ts
src/steps/resource-manager/authorization/constants.ts
src/steps/resource-manager/resources/__recordings__/iterateResourceGroups_1431284941/recording.har
src/steps/resource-manager/resources/__recordings__/resource-manager-step-resource-groups_2102244318/recording.har
src/steps/resource-manager/resources/client.test.ts
src/steps/resource-manager/resources/client.ts
src/steps/resource-manager/resources/constants.ts
src/steps/resource-manager/resources/converters.test.ts
src/steps/resource-manager/resources/converters.ts
src/steps/resource-manager/resources/index.test.ts
src/steps/resource-manager/resources/index.ts
yarn.lock

Added `azure_resource_group` entities. 
Also created direct relationships between `azure_role_assignment--ALLOWS-->azure_resource_group`.

Add azure resource groups

---

src/validateInvocation.ts

The sentry bug tagged below isn't exposing any of the causes of this error. Logging for more visibility in debugging.
https://dev.azure.com/jupiterone/Integrations/_workitems/edit/1/

Log validation context errors

---

CHANGELOG.md
docs/jupiterone.md
package.json
src/azure/resource-manager/client.ts
src/getStepStartStates.test.ts
src/getStepStartStates.ts
src/index.ts
src/steps/resource-manager/authorization/constants.ts
src/steps/resource-manager/resources/index.test.ts
src/steps/resource-manager/resources/index.ts
src/steps/resource-manager/subscriptions/__recordings__/iterateSubscriptions_501493/recording.har
src/steps/resource-manager/subscriptions/__recordings__/resource-manager-step-resource-groups_2102244318/recording.har
src/steps/resource-manager/subscriptions/client.test.ts
src/steps/resource-manager/subscriptions/client.ts
src/steps/resource-manager/subscriptions/constants.ts
src/steps/resource-manager/subscriptions/converters.test.ts
src/steps/resource-manager/subscriptions/converters.ts
src/steps/resource-manager/subscriptions/index.test.ts
src/steps/resource-manager/subscriptions/index.ts
yarn.lock

Adds the following:
- `azure_subscription` entities (should be one, considering we authenticate with a `subscriptionId`
- `azure_subscription--HAS-->azure_resource_group` relationships
Also updates the `role_assignment--ALLOWS-->azure_subscription` relationship, which was previously mapped.
Find a graph of `azure_subscription--HAS-->azure_resource_group--HAS--><resource>` below:

Add azure subscriptions

---

CHANGELOG.md
package.json
src/steps/resource-manager/utils/createResourceGroupResourceRelationship.ts

- Fixed a bug where `resourceGroupId` needed to be case-insensitive

Release 4.4.1

---

CHANGELOG.md
docs/jupiterone.md
package.json
src/getStepStartStates.test.ts
src/getStepStartStates.ts
src/index.ts
src/steps/resource-manager/api-management/__recordings__/iterateApiManagementServiceApis_2170651250/recording.har
src/steps/resource-manager/api-management/__recordings__/iterateApiManagementServices_543312516/recording.har
src/steps/resource-manager/api-management/__recordings__/resource-manager-step-api-management-apis_837383619/recording.har
src/steps/resource-manager/api-management/__recordings__/resource-manager-step-api-management-services_1373891418/recording.har
src/steps/resource-manager/api-management/client.test.ts
src/steps/resource-manager/api-management/client.ts
src/steps/resource-manager/api-management/constants.ts
src/steps/resource-manager/api-management/converters.test.ts
src/steps/resource-manager/api-management/converters.ts
src/steps/resource-manager/api-management/index.test.ts
src/steps/resource-manager/api-management/index.ts
src/steps/resource-manager/utils/findOrBuildResourceEntityFromResourceId.ts
terraform/api-management.tf
terraform/vars.tf
yarn.lock

- Added `azure_api_management_service` entities
- Added `azure_resource_group|has|azure_api_management_service` relationships
- Added `azure_api_management_api` entities
- Added `azure_api_management_service|has|azure_api_management_api`
relationships
**EXAMPLE**

Add api management

---

CHANGELOG.md
package.json

- Added `azure_api_management_service` entities
- Added `azure_resource_group|has|azure_api_management_service` relationships
- Added `azure_api_management_api` entities
- Added `azure_api_management_service|has|azure_api_management_api`
relationships

Release 5.1.0

---

CHANGELOG.md
docs/jupiterone.md
package.json
src/getStepStartStates.test.ts
src/getStepStartStates.ts
src/index.ts
src/steps/resource-manager/private-dns/__recordings__/iteratePrivateDnsRecordSets_1114316147/recording.har
src/steps/resource-manager/private-dns/__recordings__/iteratePrivateDnsZones_867025502/recording.har
src/steps/resource-manager/private-dns/__recordings__/resource-manager-step-private-dns-record-sets_3220285724/recording.har
src/steps/resource-manager/private-dns/__recordings__/resource-manager-step-private-dns-zones_199134906/recording.har
src/steps/resource-manager/private-dns/__snapshots__/converters.test.ts.snap
src/steps/resource-manager/private-dns/client.test.ts
src/steps/resource-manager/private-dns/client.ts
src/steps/resource-manager/private-dns/constants.ts
src/steps/resource-manager/private-dns/converters.test.ts
src/steps/resource-manager/private-dns/converters.ts
src/steps/resource-manager/private-dns/index.test.ts
src/steps/resource-manager/private-dns/index.ts
src/steps/resource-manager/utils/findOrBuildResourceEntityFromResourceId.ts
terraform/private-dns.tf
yarn.lock

Add private dns

---

CHANGELOG.md
docs/development.md
package.json
src/getStepStartStates.test.ts
src/getStepStartStates.ts
src/index.ts
src/types.ts
src/validateInvocation.test.ts
src/validateInvocation.ts

This change allows users to set `ingestResourceManager` to `false`.

Make subscription id optional

---

src/steps/resource-manager/api-management/index.test.ts
src/steps/resource-manager/authorization/index.test.ts
src/steps/resource-manager/batch/converters.test.ts
src/steps/resource-manager/batch/index.test.ts
src/steps/resource-manager/cdn/converters.test.ts
src/steps/resource-manager/cdn/index.test.ts
src/steps/resource-manager/container-instance/converters.test.ts
src/steps/resource-manager/container-instance/index.test.ts
src/steps/resource-manager/container-registry/converters.test.ts
src/steps/resource-manager/container-registry/index.test.ts
src/steps/resource-manager/dns/converters.test.ts
src/steps/resource-manager/dns/index.test.ts
src/steps/resource-manager/event-grid/index.test.ts
src/steps/resource-manager/private-dns/converters.test.ts
src/steps/resource-manager/private-dns/index.test.ts
src/steps/resource-manager/redis-cache/converters.test.ts
src/steps/resource-manager/redis-cache/index.test.ts
src/steps/resource-manager/resources/index.test.ts
src/steps/resource-manager/service-bus/converters.test.ts
src/steps/resource-manager/service-bus/index.test.ts
src/steps/resource-manager/storage/index.test.ts
src/steps/resource-manager/subscriptions/index.test.ts

I wanted to do a bit of test cleanup to adopt some recent SDK interface changes.

Update testing conventions

---

CHANGELOG.md
src/azure/resource-manager/client.ts
src/steps/resource-manager/storage/__recordings__/iterateQueeus-unsupported-account_2975044805/recording.har
src/steps/resource-manager/storage/__recordings__/iterateTables-unsupported-account_2123659476/recording.har
src/steps/resource-manager/storage/client.test.ts
src/steps/resource-manager/storage/client.ts

Adding logging to investigate a customer issue throwing `Error: Queue is not supported for the account.`

Add logs in iterateTables & Queues for insight into bug

---

CHANGELOG.md
src/steps/resource-manager/storage/converters.test.ts
src/steps/resource-manager/storage/converters.ts

Disallow objects in  array property

---

CHANGELOG.md
src/steps/resource-manager/databases/sql/converters.ts

Request to add `loggingEnabled` property to database entities.

Add loggingEnabled property

---

CHANGELOG.md
src/steps/resource-manager/storage/client.test.ts
src/steps/resource-manager/storage/client.ts

Handle 'OperationNotAllowedOnKind' storage account errors

---

CHANGELOG.md
src/azure/graph/authenticate.test.ts
src/azure/graph/authenticate.ts

Throw auth error when invalid client secret provided

---

CHANGELOG.md
package.json

Closes out 4 small fixes in this project.

Release 5.5.1

---

CHANGELOG.md
package.json

Releases: https://github.com/JupiterOne/graph-azure/pull/193

Release v5.7.0

---

CHANGELOG.md
package.json

Add some client error handling and retries for both the Graph API and Resource Manager API.

Release 5.10.1

---

CHANGELOG.md
src/steps/resource-manager/batch/__recordings__/resource-manager-step-batch-accounts_1786796716/recording.har
src/steps/resource-manager/batch/__snapshots__/converters.test.ts.snap
src/steps/resource-manager/batch/converters.ts
src/steps/resource-manager/batch/index.test.ts
src/steps/resource-manager/batch/index.ts
src/steps/resource-manager/monitor/converters.ts
src/steps/resource-manager/utils/normalizeId.test.ts
src/steps/resource-manager/utils/normalizeId.ts
terraform/batch.tf

-  5.3 Ensure that Diagnostic Logs are enabled for all services which support it. (Automated)
- Unlike diagnostic logs that capture activity for the …

Diagnostic Settings for Azure Batch Account

---

CHANGELOG.md
src/steps/resource-manager/event-grid/__recordings__/iterateTopicsBySubscription_2075815549/recording.har
src/steps/resource-manager/event-grid/__recordings__/resource-manager-step-event-grid-domain-topic-subscriptions_1953692490/recording.har
src/steps/resource-manager/event-grid/__recordings__/resource-manager-step-event-grid-domains_2490659508/recording.har
src/steps/resource-manager/event-grid/__recordings__/resource-manager-step-event-grid-topic-subscriptions_1748134953/recording.har
src/steps/resource-manager/event-grid/__recordings__/resource-manager-step-event-grid-topics_2972238543/recording.har
src/steps/resource-manager/event-grid/index.test.ts
src/steps/resource-manager/event-grid/index.ts
terraform/event-grid.tf
terraform/main.tf

-  5.3 Ensure that Diagnostic Logs are enabled for all services which support it. (Automated)
- Unlike diagnostic logs that capture activity for the …

Diagnostic Settings for Azure Event Grid

---

CHANGELOG.md
CODEOWNERS
package.json
src/steps/resource-manager/utils/flatten.ts
src/types.ts
src/utils/hasSubscriptionId.test.ts
src/utils/hasSubscriptionId.ts

Fix hasSubscriptionId() when subscriptionId=null

---

CHANGELOG.md
package.json
src/steps/resource-manager/databases/index.ts
src/steps/resource-manager/databases/mariadb/__recordings__/iterateMariaDBDatabases_1949020815/recording.har
src/steps/resource-manager/databases/mariadb/__recordings__/iterateMariaDBServers_2188255673/recording.har
src/steps/resource-manager/databases/mariadb/__recordings__/resource-manager-step-mariadb-servers-and-databases_601965491/recording.har
src/steps/resource-manager/databases/mariadb/client.test.ts
src/steps/resource-manager/databases/mariadb/constants.ts
src/steps/resource-manager/databases/mariadb/index.test.ts
src/steps/resource-manager/databases/mariadb/index.ts
src/steps/resource-manager/databases/mysql/__recordings__/resource-manager-step-mysql-servers-and-databases_3407319069/recording.har
src/steps/resource-manager/databases/mysql/constants.ts
src/steps/resource-manager/databases/mysql/index.test.ts
src/steps/resource-manager/databases/mysql/index.ts
src/steps/resource-manager/databases/postgresql/__recordings__/iteratePostgreSQLDatabases_3196115743/recording.har
src/steps/resource-manager/databases/postgresql/__recordings__/iteratePostgreSQLServers_997177801/recording.har
src/steps/resource-manager/databases/postgresql/__recordings__/resource-manager-step-postgresql-servers-and-databases_1676110323/recording.har
src/steps/resource-manager/databases/postgresql/client.test.ts
src/steps/resource-manager/databases/postgresql/constants.ts
src/steps/resource-manager/databases/postgresql/index.test.ts
src/steps/resource-manager/databases/postgresql/index.ts
src/steps/resource-manager/databases/sql/__recordings__/resource-manager-step-sql-servers-and-databases_2042001083/recording.har
src/steps/resource-manager/databases/sql/constants.ts
src/steps/resource-manager/databases/sql/index.test.ts
src/steps/resource-manager/databases/sql/index.ts
terraform/storage.tf
yarn.lock

-  5.3 Ensure that Diagnostic Logs are enabled for all services which support it. (Automated)
- Unlike diagnostic logs that capture activity for the …

Diagnostic Settings for Azure Databases (PostgreSQL, MariaDB, SQL, MySQL)

---

CHANGELOG.md
docs/jupiterone.md
package.json
src/steps/active-directory/__recordings__/active-directory-steps_52759203/recording.har
src/steps/active-directory/__recordings__/fetchIdentitySecurityDefaultsEnforcementPolicy-with-permission_3595030718/recording.har
src/steps/active-directory/__recordings__/fetchIdentitySecurityDefaultsEnforcementPolicy-without-permission_662264354/recording.har
src/steps/active-directory/client.test.ts
src/steps/active-directory/client.ts
src/steps/active-directory/converters.test.ts
src/steps/active-directory/converters.ts
src/steps/active-directory/index.ts
src/steps/resource-manager/network/index.test.ts

This stuff was a bit of a head scratcher. Thanks @mknoedel for your help yesterday.
Let me know if you'd like more explanation anywhere.

Cis benchmark 1.22

---

CHANGELOG.md
src/steps/active-directory/client.test.ts
src/steps/active-directory/client.ts

Change job name from 'missing_optional_permissions' to 'auth'

---

CHANGELOG.md
docs/jupiterone.md
src/getStepStartStates.test.ts
src/getStepStartStates.ts
src/steps/resource-manager/databases/sql/index.test.ts
src/steps/resource-manager/network/__recordings__/iterateNetworkSecurityGroupFlowLogs_15156037/recording.har
src/steps/resource-manager/network/__recordings__/iterateNetworkWatchers_3770039924/recording.har
src/steps/resource-manager/network/__recordings__/rm-network-flow-logs_1050087510/recording.har
src/steps/resource-manager/network/__recordings__/rm-network-watchers_532923575/recording.har
src/steps/resource-manager/network/client.test.ts
src/steps/resource-manager/network/client.ts
src/steps/resource-manager/network/constants.ts
src/steps/resource-manager/network/converters/index.ts
src/steps/resource-manager/network/index.test.ts
src/steps/resource-manager/network/index.ts
terraform/.gitignore
test/helpers/getMockAccountEntity.ts

This graph is a little messy with all of the diagnostic settings, but note the `azure_security_group_flow_logs` entity and its three relationships.

Add azure_network_watcher and azure_security_group_flow_logs

---

CHANGELOG.md
docs/jupiterone.md
src/getStepStartStates.test.ts
src/getStepStartStates.ts
src/steps/resource-manager/advisor/index.test.ts
src/steps/resource-manager/authorization/constants.ts
src/steps/resource-manager/monitor/constants.ts
src/steps/resource-manager/monitor/index.ts
src/steps/resource-manager/resources/index.ts
src/steps/resource-manager/security/constants.ts
src/steps/resource-manager/security/index.test.ts
src/steps/resource-manager/security/index.ts
src/steps/resource-manager/subscriptions/__recordings__/iterateLocations_3147255615/recording.har
src/steps/resource-manager/subscriptions/__recordings__/rm-subscription-locations_2346918759/recording.har
src/steps/resource-manager/subscriptions/client.test.ts
src/steps/resource-manager/subscriptions/client.ts
src/steps/resource-manager/subscriptions/constants.ts
src/steps/resource-manager/subscriptions/converters.ts
src/steps/resource-manager/subscriptions/index.test.ts
src/steps/resource-manager/subscriptions/index.ts

Cis benchmark 6.5

---

CHANGELOG.md
src/steps/resource-manager/compute/__recordings__/rm-compute-virtual-machines_2119333431/recording.har
src/steps/resource-manager/compute/constants.ts
src/steps/resource-manager/compute/converters.test.ts
src/steps/resource-manager/compute/converters.ts
src/steps/resource-manager/compute/index.test.ts
src/steps/resource-manager/compute/index.ts

The `usesManagedDisk` property will help to answer CIS Benchmark 7.1.
I've done some testing of Azure VMs on my own, and it **appears** that if the VM uses a managed OS disk, it _must_ use managed data disks, and if the VM uses an unmanaged OS disk, it _must_ use unmanaged data disks. If this were true, we could simply check if the OS disk is managed to answer this question.
In any case, the implementation of `usesManagedDisks` is thorough enough to handle even cases where this isn't true.
Additionally, this change fixes a bug I noticed when creating VM -> disk relationships.

Cis benchmark 7.1

---

CHANGELOG.md
docs/jupiterone.md
package.json
src/getStepStartStates.test.ts
src/getStepStartStates.ts
src/steps/resource-manager/advisor/constants.ts
src/steps/resource-manager/advisor/index.test.ts
src/steps/resource-manager/advisor/index.ts
src/steps/resource-manager/security/__recordings__/iteratePricings_1473993610/recording.har
src/steps/resource-manager/security/__recordings__/rm-security-center-pricing-configs_1738543608/recording.har
src/steps/resource-manager/security/client.test.ts
src/steps/resource-manager/security/client.ts
src/steps/resource-manager/security/constants.ts
src/steps/resource-manager/security/converters.ts
src/steps/resource-manager/security/index.test.ts
src/steps/resource-manager/security/index.ts
yarn.lock

Cis benchmark 4.2.1

---

CHANGELOG.md
package.json
src/steps/resource-manager/compute/index.test.ts
src/steps/resource-manager/compute/index.ts
src/steps/resource-manager/network/index.ts
src/steps/resource-manager/subscriptions/index.ts

I also decided to go back and change some recent `logger.error` statements to `logger.warn`.

Release 5.17.0

---

CHANGELOG.md
package.json
src/steps/resource-manager/databases/sql/client.test.ts

```markdown
- Added the following properties to `azure_sql_server`:
- `encryptionProtector.serverKeyName`
- `encryptionProtector.serverKeyType`
- Added `azure_sql_server_active_directory_admin` entities.
```

Changelog for 5.18.0

---

CHANGELOG.md
package.json

```
- Added `azure_monitor_activity_log_alert_monitors_scope` relationships
- Added `azure_monitor_activity_log_alert` entities
```

Release 5.20.0

---

terraform/main.tf

A small change that helps when testing diagnostic settings.

Add subscription diagnostic setting in terraform

---

CHANGELOG.md
package.json
src/steps/resource-manager/databases/converters.ts
src/steps/resource-manager/storage/converters.ts
src/steps/resource-manager/storage/index.ts
yarn.lock

```
- Upgraded `@jupiterone/integration-sdk-*@5.11.2`
```

Upgrade @jupiterone/integration-sdk-*@5.11.2

---

CHANGELOG.md
package.json
src/steps/resource-manager/databases/converters.ts
src/steps/resource-manager/storage/client.test.ts
src/steps/resource-manager/storage/client.ts
src/steps/resource-manager/storage/converters.ts
src/steps/resource-manager/storage/index.test.ts
src/steps/resource-manager/storage/index.ts
yarn.lock

- Added checks to ensure storage account `Kind` supports file and blobs before
attempting to fetch file and blob resources.

File shares not supported for storage account

---

CHANGELOG.md
src/azure/resource-manager/__recordings__/authenticate-no-subscription_194703208/recording.har
src/azure/resource-manager/authenticate.test.ts
src/azure/resource-manager/authenticate.ts

Need to be able to authenticate a client without a subscription Id for the proper createSubscriptionInstances flow

AB#3555 Remove subscriptionId check for using an authenticated client

---

CHANGELOG.md
package.json
src/steps/resource-manager/security/constants.ts
src/steps/resource-manager/security/converters.ts

```
- Added the `enabled` property to `azure_security_center_setting` entities.
```
I went ahead and versioned to get this out quicker.

Add azure_security_center_setting.enabled

---

CHANGELOG.md
package.json

```
- Added logger.warn statement when getPolicyDefinition API call fails.
```

Release 5.23.5

---

CHANGELOG.md
docs/jupiterone.md
src/getStepStartStates.test.ts
src/getStepStartStates.ts
src/steps/resource-manager/network/__recordings__/rm-network-private-endpoint-subnet-relationships_3673583091/recording.har
src/steps/resource-manager/network/constants.ts
src/steps/resource-manager/network/index.test.ts
src/steps/resource-manager/network/index.ts

See #321 
Note that this private endpoint resource has direct relationships to **resource group**, **subnet**, **network interface** and then a target resource (in this case, the storage account called `ndowmon11j1dev`).

Ingest subnet -> private endpoint relationships

---

CHANGELOG.md
docs/jupiterone.md
src/getStepStartStates.test.ts
src/getStepStartStates.ts
src/steps/resource-manager/network/__recordings__/rm-network-private-endpoint-nic-relationships_3055566992/recording.har
src/steps/resource-manager/network/constants.ts
src/steps/resource-manager/network/index.test.ts
src/steps/resource-manager/network/index.ts

Ingest private endpoint -> nic relationships

---

src/steps/resource-manager/network/__recordings__/iteratePrivateEndpoints_3588815898/recording.har
src/steps/resource-manager/network/__recordings__/rm-network-private-endpoint-nic-relationships_3055566992/recording.har
src/steps/resource-manager/network/__recordings__/rm-network-private-endpoint-subnet-relationships_3673583091/recording.har
src/steps/resource-manager/network/__recordings__/rm-network-private-endpoints_2510984550/recording.har
src/steps/resource-manager/network/index.test.ts
terraform/compute.tf
terraform/keyvault.tf

Adds terraform for `azurerm_private_endpoint` and re-records a few tests.

Add terraform for azurerm_private_endpoint

---

CHANGELOG.md
docs/jupiterone.md
src/getStepStartStates.test.ts
src/getStepStartStates.ts
src/steps/resource-manager/network/__recordings__/rm-network-private-endpoint-resource-relationships_2489136482/recording.har
src/steps/resource-manager/network/constants.ts
src/steps/resource-manager/network/index.test.ts
src/steps/resource-manager/network/index.ts

321 private endpoint resource relationships

---

CHANGELOG.md
docs/jupiterone.md
src/getStepStartStates.test.ts
src/getStepStartStates.ts
src/steps/resource-manager/network/__recordings__/iteratePrivateEndpoints_3588815898/recording.har
src/steps/resource-manager/network/__recordings__/rm-network-private-endpoint-nic-relationships_3055566992/recording.har
src/steps/resource-manager/network/__recordings__/rm-network-private-endpoint-resource-relationships_2489136482/recording.har
src/steps/resource-manager/network/__recordings__/rm-network-private-endpoint-subnet-relationships_3673583091/recording.har
src/steps/resource-manager/network/__recordings__/rm-network-private-endpoints_2510984550/recording.har
src/steps/resource-manager/network/client.test.ts
src/steps/resource-manager/network/client.ts
src/steps/resource-manager/network/constants.ts
src/steps/resource-manager/network/converters/index.ts
src/steps/resource-manager/network/index.test.ts
src/steps/resource-manager/network/index.ts
terraform/compute.tf
terraform/keyvault.tf

Ingest private endpoints

---

CHANGELOG.md
docs/jupiterone.md
src/getStepStartStates.test.ts
src/getStepStartStates.ts
src/steps/resource-manager/appservice/__recordings__/rm-appservice-app-plan-relationships_169005199/recording.har
src/steps/resource-manager/appservice/client.test.ts
src/steps/resource-manager/appservice/constants.ts
src/steps/resource-manager/appservice/index.test.ts
src/steps/resource-manager/appservice/index.ts

Ingest app -> service plan relationhsips

---

CHANGELOG.md
docs/jupiterone.md
src/getStepStartStates.test.ts
src/getStepStartStates.ts
src/steps/resource-manager/appservice/__recordings__/iterateAppServicePlans_4213262849/recording.har
src/steps/resource-manager/appservice/__recordings__/rm-appservice-app-plan-relationships_169005199/recording.har
src/steps/resource-manager/appservice/__recordings__/rm-appservice-app-service-plans_1428281048/recording.har
src/steps/resource-manager/appservice/client.test.ts
src/steps/resource-manager/appservice/client.ts
src/steps/resource-manager/appservice/constants.ts
src/steps/resource-manager/appservice/converters.ts
src/steps/resource-manager/appservice/index.test.ts
src/steps/resource-manager/appservice/index.ts

The next PR will create relationships between apps & app service plans. This will allow users to identify the SKU of all of their function apps.

319 app service plans

---

CHANGELOG.md
src/getStepStartStates.test.ts
src/getStepStartStates.ts
src/steps/active-directory/__recordings__/active-directory-steps_52759203/recording.har
src/steps/active-directory/__recordings__/iterateCredentialUserRegistrationDetails_624328060/recording.har
src/steps/active-directory/client.test.ts
src/steps/active-directory/client.ts
src/steps/active-directory/constants.ts
src/steps/active-directory/converters.test.ts
src/steps/active-directory/converters.ts
src/steps/active-directory/index.test.ts
src/steps/active-directory/index.ts

Add isMfaRegistered property to user

---

CHANGELOG.md

```
- Added ingestion of Azure Management Groups when the
`configureSubscriptionInstances` configuration field is `true`. This ingestion
requires users to assign the `Management Group Reader`
[role](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#management-group-reader)
to the service principal used in the given integration configuration to the
**Tenant Root Group**
[management group](https://docs.microsoft.com/en-us/azure/governance/management-groups/overview#root-management-group-for-each-directory).
- Added support for ingesting the following **new** resources:
| Service           | Resource / Entity        |
| ----------------- | ------------------------ |
| Gallery           | `azure_gallery`          |
| Gallery Image     | `azure_shared_image`     | …
```

Changelog for 5.25.0

---

CHANGELOG.md
package.json

```
| Source     | \_class | Target                    |
| ---------- | ------- | ------------------------- |
| `azure_vm` | `USES`  | `azure_service_principal` |
```

Changelog for 5.26.0

---

CHANGELOG.md
src/steps/resource-manager/authorization/converters.test.ts
src/steps/resource-manager/authorization/converters.ts
src/steps/resource-manager/authorization/index.ts

```
- New properties added to resources:
| Entity                  | Properties                                               |
| ----------------------- | -------------------------------------------------------- |
| `azure_role_assignment` | `actions`, `dataActions`, `notActions`, `notDataActions` |
```

Add actions to azure_role_assignment

---

CHANGELOG.md
package.json

```
- New properties added to resources:
| Entity                  | Properties                                               |
| ----------------------- | -------------------------------------------------------- |
| `azure_role_assignment` | `actions`, `dataActions`, `notActions`, `notDataActions` |
```

Changelog for 5.27.0

---

CHANGELOG.md
package.json

```
- Added support for ingesting the following **new** resources:
| Service               | Resource / Entity            |
| --------------------- | ---------------------------- |
| Gallery Image Version | `azure_shared_image_version` |
| Source               | \_class | Target                       |
| -------------------- | ------- | ---------------------------- |
| `azure_shared_image` | `HAS`   | `azure_shared_image_version` |
| `azure_vm`           | `USES`  | `azure_shared_image_version` |
- New properties added to resources:
| Entity                    | Properties                                  |
| ------------------------- | ------------------------------------------- |
| `azure_policy_definition` | …
```

Changelog for 5.28.0

---

CHANGELOG.md
package.json
src/steps/resource-manager/compute/converters.ts

Add publishedDate, createdOn to azure_shared_image_version

---

src/steps/active-directory/client.ts

Noticed this while doing some other work in this project.

Log err from callback errors in graph client

---

CHANGELOG.md
src/steps/resource-manager/dns/__recordings__/resource-manager-step-dns-zones_89672344/recording.har
src/steps/resource-manager/dns/__recordings__/rm-dns-zone-NotRegistered_3055585279/recording.har
src/steps/resource-manager/dns/index.test.ts
src/steps/resource-manager/dns/index.ts
src/steps/resource-manager/private-dns/__recordings__/resource-manager-step-private-dns-zones_199134906/recording.har
src/steps/resource-manager/private-dns/__recordings__/rm-private-dns-zone-NotRegistered_2397656873/recording.har
src/steps/resource-manager/private-dns/index.test.ts
src/steps/resource-manager/private-dns/index.ts
src/steps/resource-manager/resources/client.ts
test/helpers/recording.ts

Microsoft responds with the following when the subscription has not "registered" Microsoft.Network.
```
{
"code": "BadRequest",
"message": "The specified subscription df44baaf-f737-48d5-ab23-020a20fa94da does not exist"
}
```
This has only been seen on DNS Zones and Private DNS Zones so far. This is the most frequent unhandled error in our performance monitoring tool currently.

Check for Microsoft.Network provider registration before fetching DNS zones

---

src/azure/graph/__recordings__/fetchOrganization-invalid-token_1917593506/recording.har
src/azure/graph/client.test.ts
src/azure/graph/client.ts

A bit of cleanup before the next PR. No functional changes.

Add test for /organization endpoint

---

CHANGELOG.md
src/azure/graph/__recordings__/refresh-access-token_2395700497/recording.har
src/azure/graph/client.test.ts
src/azure/graph/client.ts

This solves the following errors:
- "Your access token has expired. Please renew it before submitting the request."
- "Access token has expired or is not yet valid."
- "CompactToken parsing failed with error code: 80049217"

Support refreshing tokens in graph client

---

.github/workflows/build.yml
CHANGELOG.md
build.sh
jupiterone/questions/questions.yaml
package.json
tsconfig.dist.json

We'll need to get `JUPITERONE_ACCOUNT_ID` and `JUPITERONE_API_KEY` secrets added to this repo.
```
- Open-sourced Azure managed questions
```

open-source managed questions

---

CHANGELOG.md
src/steps/resource-manager/interservice/index.ts

- Fixed `DUPLICATE_KEY_DETECTED` in `rm-compute-network-relationships` step

Int 4067 rm compute network relationships duplicate key

---

CHANGELOG.md
docs/jupiterone.md
package.json
src/getStepStartStates.test.ts
src/getStepStartStates.ts
src/index.ts
src/steps/active-directory/constants.ts
src/steps/resource-manager/authorization/constants.ts
src/steps/resource-manager/authorization/index.test.ts
src/steps/resource-manager/container-services/index.test.ts
src/steps/resource-manager/dns/index.test.ts
src/steps/resource-manager/frontdoor/__recordings__/rm-fetch-frontdoors_1342294312/recording.har
src/steps/resource-manager/frontdoor/client.ts
src/steps/resource-manager/frontdoor/constants.ts
src/steps/resource-manager/frontdoor/converters.ts
src/steps/resource-manager/frontdoor/index.test.ts
src/steps/resource-manager/frontdoor/index.ts
src/steps/resource-manager/private-dns/index.test.ts
src/steps/resource-manager/resources/index.test.ts
src/steps/resource-manager/service-bus/index.test.ts
src/steps/resource-manager/storage/client.test.ts
src/steps/resource-manager/storage/index.test.ts
test/integrationInstanceConfig.ts
yarn.lock

- Added `azure_frontdoor` entities

Int 4181 ingest azure frontdoor entities

---

docs/jupiterone.md

Fixed some weirdness that happened in https://github.com/JupiterOne/graph-azure/pull/518

Merge main into `janette-anchor` branch

---

docs/jupiterone.md

Supercedes #524, which had some strange formatting behavior on the existing table.

Add anchor

---

docs/jupiterone.md

We are changing all integration article titles to just the actual integration name.

Change title

---

CHANGELOG.md

Just catching up on the changelog, which was missed in the last PR.

Changelog for 5.40.0

---

cli/log.ts
src/steps/resource-manager/batch/__recordings__/rm-batch-applications_1989667083/recording.har
src/steps/resource-manager/batch/index.test.ts
src/steps/resource-manager/batch/index.ts

The error in this ticket [https://jupiterone.atlassian.net/browse/INT-5201](url) occurs when you try to list the batch applications in an account that is not linked to an auto-storage account. You are unable to create an application if the account is currently unlink to an auto-storage account but the account can be unlinked after application is created.
Steps I did to setup azure to produce this error: 
1. Create Batch Account that is linked to an auto-storage account
2. Create Batch Application
3. Select "None" when selecting a storage account under the "Storage account" tab
This adds a check that autoStorage (defined in rawData of batch account) is defined before iterating through batch applications for that account

INT-5201 Batch Application Failures

---

src/steps/resource-manager/subscriptions/client.ts

The job that paginates this api failed, this should solve it

Correction of next link subscription spec

---

src/azure/resource-manager/client.test.ts
src/azure/resource-manager/client.ts
src/steps/resource-manager/policy/converters.ts
src/steps/resource-manager/security/converters.ts

Should reduce the amount of errors we are logging with undefined messages and in general those that are of the form `The current subscription type is not permitted to perform operations on any provider namespace. Please use a different subscription.`

Added some new error parsing and other checks on entity creation

---

jupiterone/questions/questions.yaml

adding a couple questions/few queries in relation to this blog post https://www.jupiterone.com/blog/investigate-new-toxic-combination-default-common-configurations-in-jupiterone

Add allowSharedKeyAccess and listKeys permission questions

---

.github/workflows/codeql-analysis.yml
src/steps/active-directory/client.test.ts
src/steps/active-directory/client.ts
src/steps/resource-manager/appservice/index.ts
src/steps/resource-manager/batch/index.test.ts
src/steps/resource-manager/compute/converters.test.ts
src/steps/resource-manager/key-vault/client.ts
src/steps/resource-manager/storage/index.test.ts

- update job event names to SDK supported values
- format changes
This is the first part in providing users with a better indication of an integrations health.

Consolidating Job Event Names to SDK supported values

---

package.json
yarn.lock

- Reduced log level of graph object uploads from info to debug

Bump SDK Version

---

docs/jupiterone.md
src/getStepStartStates.test.ts
src/getStepStartStates.ts
src/steps/resource-manager/compute/__recordings__/rm-virtual-machines-scale-sets-image-relationships_2086223172/recording.har
src/steps/resource-manager/compute/__recordings__/rm-virtual-machines-scale-sets-image-version-relationships_148061297/recording.har
src/steps/resource-manager/compute/__recordings__/rm-virtual-machines-scale-sets-relationships_642486692/recording.har
src/steps/resource-manager/compute/constants.ts
src/steps/resource-manager/compute/converters.ts
src/steps/resource-manager/compute/index.test.ts
src/steps/resource-manager/compute/index.ts
src/steps/resource-manager/interservice/constants.ts
src/steps/resource-manager/interservice/index.test.ts
src/steps/resource-manager/interservice/index.ts

Added 3 relationships between entities on compute:
```
VIRTUAL_MACHINE_USES_SCALE_SETS: {
_type: 'azure_vm_uses_scale_set',
sourceType: entities.VIRTUAL_MACHINE._type,
_class: RelationshipClass.USES,
targetType: entities.VIRTUAL_MACHINE_SCALE_SET._type,
},
VM_SCALE_SETS_USES_SHARED_IMAGE_VERSION: {
_type: 'azure_vm_scale_set_uses_shared_image_version',
sourceType: entities.VIRTUAL_MACHINE_SCALE_SET._type,
_class: RelationshipClass.USES,
targetType: entities.SHARED_IMAGE._type,
},
VM_SCALE_SETS_USES_SHARED_IMAGE: {
_type: 'azure_vm_scale_set_uses_shared_image',
sourceType: entities.VIRTUAL_MACHINE_SCALE_SET._type,
_class: RelationshipClass.USES,
targetType: entities.SHARED_IMAGE._type,
},
```
Also refactored the constants on that service.

Added vmss relationships

---

src/azure/resource-manager/client.ts
src/steps/resource-manager/authorization/client.ts
src/steps/resource-manager/policy/client.ts
src/steps/resource-manager/resources/client.ts

Change rate period of all calls related to Microsoft.Authorization scope

---

src/config.ts
src/constants.ts
src/steps/active-directory/index.ts
src/steps/resource-manager/subscriptions/executionHandlers/usageDetails.ts

Changed steps enabled by default. This is based on data retrieved from step duration: Either average or max duration of steps.
Average:
Max:

Disable steps by default

---

src/azure/resource-manager/client.ts

This was added by me last set of changes but it honestly shouldn't be there since we support only single tenant

Remove configuration

---

jupiterone/questions/questions.yaml

corrected query
added secondary bad query

fixing bad queries + adding query

---

src/steps/resource-manager/container-services/index.ts

This mapped relationships were causing issues since they where missing a target filter key

Added filter keys

---

src/steps/resource-manager/resources/client.ts

Paginate the resourcegroup client

Paginate resource groups

---

src/azure/graph/client.ts

Making retry logic for the graph endpoints more robust.

Change graph retry logic

---

src/steps/active-directory/converters.ts
src/steps/resource-manager/subscriptions/converters.ts
src/steps/resource-manager/subscriptions/executionHandlers/subscriptions.ts
test/helpers/getMockEntity.ts

Added tenantId property in azure_subscription Entity
Jira Ticket: https://jupiterone.atlassian.net/browse/IA-172

Add directory id to subscription
